---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - В каталоге у каждого товара должны быть название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Каждый товар должен иметь свою страницу с названием, рейтингом, ценаой со скидкой и без нее
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность создать заказ
  - Информация о корзине с товарами должна сохраняется даже после того, как пользователь покинул страницу
  - Информация о корзине должна храниться в сессии браузера
  - На странице каталога товаров должна быть панель пагинации для постраничного вывода товаров
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Переход по страницам сайта должен проходить без перезагрузки
  - Сайт должен иметь возможность переключения языка между русским и английским
implicit:
  - Контент должен быть расположен по центру
  - |
    Страница с каталогом должна иметь блок фильтрации с полем поиска, выподающим меню "Категория", 
    чекбоксом "В наличии", выбором диапазона цен, выподающим меню "Производитель"
  - В меню "Категория" должен быть список всех категорий товаров из каталога
  - В меню "Производитель" должен быть список всех производителей товаров из каталога
  - Поле поиска должно принимать строку и выводить список товаров содержащих эту строку в названии
  - Выбор категории из меню "Категория" должен выводить список товаров этой категории
  - Активация чекбокса "В наличии" должна выводить только товары в наличии
  - Диапазон цен должен выводить товары цена которых с учетом скидки попадает в этот диапазон
  - Выбор производителя в меню "Производитель" должен выводить товары выбрранных производителей
  - Пользователь должен иметь возможность фильтровать сразу по нескольким параметрам
  - Фильтрация должна проходить среди всех товаров магазина
  - Сайт должен иметь навигационную панель с лого, кнопкой "Магазин", кнопкой "Корзина" и панелью со сменой языка
  - Нажатие на лого должно открывать каталог
  - Кнопка "Магазин" должна открывать каталог 
  - Кнопка "Корзина" должна открывать корзину 
  - Корзина должна содержать список добавленнх товаров
  - В корзине у каждого товара должна быть кнопка "Удалить", название и цена
  - Кнопка "Удалить" в корзине должна удалять одну единицу товара из корзины  
  - В корзине должна быть общая стоимость заказа
  - В корзине должна быть кнопка "Оформить заказ"
  - Кнопка "оформить заказ" должна переводить пользователя на страницу оплаты
  - В каталоге у каждого товара должна быть кнопка "В корзину"
  - Кнопка "В корзину" должна добавлять товар в корзину
  - У кнопки "Корзина" в навигационной панели должна быть индикация количества товаров в корзине, если корзина не пуста
  - Каждый блок с товаром в каталоге при нажатии должен вести на страницу товара 
  - Каждый товар должен иметь на своей странице описание, кнопку "В корзину"
  - При нажатии на хэштег с категорией на странице товара должна открываться страница каталога с фильтрацией по данной категории
  - |
    При нажатии на кнопку "оформить заказ" должно появляться всплывающее окно оформления заказа 
    со списком товаров, общей стоимостью, кнопками "Закрыть" и "х"
  - Всплывающее окно оформления заказа должно закрываться с помощью двух кнопок "Закрыть" и "х"
