---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Контент должен быть расположен на ширину всего экрана или по центру
  - Пользователь должен иметь возможность сбрасывать настроенные фильтры 
  - Каждый товар должен иметь свою страничку с подробным описанием
  - Каждая страничка товара должна содержать название, рейтинг, цена со скидкой и без нее
  - Сайт должен иметь навигационную панель
  - Корзина должна содержать список добавленнх товаров
  - В корзине у каждого товара должна быть кнопка удаления из корзины
  - В корзине у каждого товара должно быть название, цена и колличество 
  - В корзине должна быть общая стоимость заказа
  - В корзине должна быть кнопка "оформить заказ"
  - Кнопка "оформить заказ" должна переводить пользователя на страницу оплаты
  - В каталоге у каждого товара должны быть название, рейтинг, цена со скидкой и без нее, кнопка добавления в корзину
  - На странице каталога товаров должна быть панель пагинации 
  - Переход по страницам сайта должен проходить без перезагрузки
  
