---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Контент должен быть расположен на ширину всего экрана или по центру
  - |
    Страница с каталогом должна иметь блок фильтрации с полем поиска, выподающим меню "Категория", 
    чекбоксом "В наличии", выбором диапазона цен, выподающим меню "Производитель"
  - Поле поиска должно принимать строку и выводить список товаров содержащих эту строку в названии
  - Выбор категории из меню "Категория" должен выводить список товаров этой категории
  - Активация чекбокса "В наличии" должна выводить только товары в наличии
  - Диапазон цен должен выводить товары цена которых с учетом скидки попадает в этот диапазон
  - Выбор производителя в меню "Производитель" должен выводить товары выбрранных производителей
  - Пользователь должен иметь возможность фильтровать сразу по нескольким параметрам
  - Пользователь должен иметь возможность сбрасывать настройки фильтра 
  - Сайт должен иметь навигационную панель с лого, кнопкой "Магазин", кнопкой "Корзина"
  - Нажатие на лого должно открывать каталог
  - Кнопка "Магазин" должна открывать каталог 
  - Кнопка "Корзина" должна открывать корзину 
  - Корзина должна содержать список добавленнх товаров
  - |
    В корзине у каждого товара должна быть кнопка "Удалить", панель увеличения или уменьшения количества товара, 
    название и цена
  - Кнопка "Удалить" в корзине должна удалять товар из корзины  
  - Панель увеличение, уменьшения количества товара на странице корзины должна изменять колличество товара в корзине
  - В корзине должна быть общая стоимость заказа
  - В корзине должна быть кнопка "Оформить заказ"
  - Кнопка "оформить заказ" должна переводить пользователя на страницу оплаты
  - В каталоге у каждого товара должны быть название, рейтинг, цена со скидкой и без нее, кнопка "В корзину"
  - Кнопка "В корзину" должна добавлять товар в корзину
  - При нажатии кнопки "В корзину" кнопка должна меняться на панель увеличение, уменьшения количества товара 
  - Панель увеличение, уменьшения количества товара на странице каталога должна изменять колличество товара в корзине
  - При нажатии кнопки "В корзину" у кнопки "Корзина" в навигационной панели должно появляться колличество товаров  
  - Каждый блок с товаром в каталоге при нажатии должен вести на страницу товара 
  - Каждый товар должен иметь свою страничку с названием, описанием, рейтингом, ценаой со скидкой и без нее, кнопкой "В корзину"
  - На странице каталога товаров должна быть панель пагинации 
  - Переход по страницам сайта должен проходить без перезагрузки
  
